-- BASE DE DATOS PARA LAS CONFIRMACIONES
-- Ejecuta este script en Supabase > SQL Editor.

create table if not exists public.confirmaciones (
  id bigint generated by default as identity primary key,
  nombre text not null,
  apellido text not null,
  asistencia text not null check (asistencia in ('Sí, asistiré', 'No podré asistir')),
  creado_en timestamptz not null default now()
);

alter table public.confirmaciones enable row level security;

-- Permite registrar confirmaciones desde la landing.
create policy "Permitir registrar confirmaciones"
on public.confirmaciones
for insert
to anon
with check (
  char_length(nombre) between 1 and 60
  and char_length(apellido) between 1 and 60
  and asistencia in ('Sí, asistiré', 'No podré asistir')
);

-- IMPORTANTE:
-- No se habilita lectura pública. Así los invitados no pueden ver
-- los nombres de las demás personas.
